sudo: false
dist: xenial
language: python
notifications:
  email: false
env:
  - FLASK_VERSION=1.1.2
  - FLASK_VERSION=0.12.2
  - FLASK_VERSION=0.11.1
  - FLASK_VERSION=0.10.1
python:
  - 3.9-dev
  - 3.8
  - 3.7
  - 3.6

stages:
  - test


jobs:
  include:
    - *moban
    - *lint

stage: test

before_install:
  - pip install Flask==$FLASK_VERSION
  - if [[ -f min_requirements.txt && "$MINREQ" -eq 1 ]]; then
      mv min_requirements.txt requirements.txt ;
    fi
  - test ! -f rnd_requirements.txt ||
    pip install --no-deps -r rnd_requirements.txt
  - test ! -f rnd_requirements.txt || pip install -r rnd_requirements.txt ;
  - pip install -r tests/requirements.txt
script:
  - make test
after_success:
  codecov
